spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath:data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
#          naver:
#            client-id:
#            client-secret:
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope:
#              - name
#              - email
#              - profile_image
#            client-name: Naver
#        provider:
#          naver:
#            authorizationUri:
#            tokenUri:
#            userInfoUri:
#            userNameAttribute:


logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
jwt:
  key: "맑은눈의광인메인프로젝트"
  access:
    header: "Authorization"
  refresh:
    header: "Refresh"
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420
