# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read
  
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./backend 

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.MAIN_CONFIG }}
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Add permission
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
      
    - name: Build with Gradle
      run: ./gradlew clean build --debug
      working-directory: ${{ env.working-directory }}

    # 테스트 코드 작성 시 추가
    # - name: Add test results as a comment to the PR
    #   uses: EnricoMi/publish-unit-test-result-action@v1
    #   if: always()
    #   with:
    #     files: '**/build/test-results/test/TEST-*.xml'

    # - name: Add Check comments to failed test lines
    #   uses: mikepenz/action-junit-report@v3
    #   if: always()
    #   with:
    #     report_paths: '**/build/test-results/test/TEST-*.xml'
    #     token: ${{ github.token }}
